/-
Copyright (c) 2026 Daniel Eric Fredriksen, Quantyra. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Eric Fredriksen
-/
import Mathlib.Algebra.FreeAlgebra
import Mathlib.Algebra.RingQuot
import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.Tactic.NoncommRing

/-!
# Abstract polynomial Weyl algebra

The polynomial Weyl algebra is presented as a quotient of the free algebra on
position and momentum generators by the three canonical commutator relations.
-/

noncomputable section

open MvPolynomial
open scoped IsMulCommutative

namespace ExoticCCR

variable (K : Type*) [Field K] (ι : Type*) [DecidableEq ι]

/-- The two kinds of generators of the polynomial Weyl algebra. -/
abbrev WeylGen := ι ⊕ ι

/-- A position generator in the free algebra. -/
def qFree (i : ι) : FreeAlgebra K (WeylGen ι) := FreeAlgebra.ι K (.inl i)

/-- A momentum generator in the free algebra. -/
def pFree (i : ι) : FreeAlgebra K (WeylGen ι) := FreeAlgebra.ι K (.inr i)

/-- Defining relations for the polynomial Weyl algebra. -/
inductive WeylRel : FreeAlgebra K (WeylGen ι) → FreeAlgebra K (WeylGen ι) → Prop
  | qq (i j : ι) : WeylRel (qFree K ι i * qFree K ι j) (qFree K ι j * qFree K ι i)
  | pp (i j : ι) : WeylRel (pFree K ι i * pFree K ι j) (pFree K ι j * pFree K ι i)
  | qp (i j : ι) : WeylRel
      (qFree K ι i * pFree K ι j - pFree K ι j * qFree K ι i)
      (algebraMap K _ (if i = j then 1 else 0))

/-- The abstract polynomial Weyl algebra. -/
abbrev PolynomialWeylAlgebra := RingQuot (WeylRel K ι)

/-- A position generator in the polynomial Weyl algebra. -/
def q (i : ι) : PolynomialWeylAlgebra K ι :=
  RingQuot.mkAlgHom K (WeylRel K ι) (qFree K ι i)

/-- A momentum generator in the polynomial Weyl algebra. -/
def p (i : ι) : PolynomialWeylAlgebra K ι :=
  RingQuot.mkAlgHom K (WeylRel K ι) (pFree K ι i)

@[simp] theorem q_mul_q (i j : ι) : q K ι i * q K ι j = q K ι j * q K ι i := by
  simpa [q] using RingQuot.mkAlgHom_rel K (WeylRel.qq (K := K) (ι := ι) i j)

@[simp] theorem p_mul_p (i j : ι) : p K ι i * p K ι j = p K ι j * p K ι i := by
  simpa [p] using RingQuot.mkAlgHom_rel K (WeylRel.pp (K := K) (ι := ι) i j)

@[simp] theorem q_mul_p_sub (i j : ι) :
    q K ι i * p K ι j - p K ι j * q K ι i =
      algebraMap K _ (if i = j then 1 else 0) := by
  simpa [q, p] using RingQuot.mkAlgHom_rel K (WeylRel.qp (K := K) (ι := ι) i j)

/-- The subalgebra generated by the commuting position generators. -/
def qSubalgebra : Subalgebra K (PolynomialWeylAlgebra K ι) :=
  Algebra.adjoin K (Set.range (q K ι))

instance qSubalgebra_isMulCommutative : IsMulCommutative (qSubalgebra K ι) :=
  Algebra.isMulCommutative_adjoin K (by
    rintro _ ⟨i, rfl⟩ _ ⟨j, rfl⟩
    exact q_mul_q K ι i j)

/-- Evaluation of a commutative polynomial at the position generators. -/
def qPolynomial : MvPolynomial ι K →ₐ[K] PolynomialWeylAlgebra K ι :=
  (qSubalgebra K ι).val.comp (MvPolynomial.aeval fun i ↦
    ⟨q K ι i, Algebra.subset_adjoin ⟨i, rfl⟩⟩)

@[simp] theorem qPolynomial_X (i : ι) : qPolynomial K ι (X i) = q K ι i := by
  simp [qPolynomial]

@[simp] theorem qPolynomial_C (a : K) :
    qPolynomial K ι (C a) = algebraMap K _ a := by
  simp [qPolynomial]

/-- Polynomial-position coefficients satisfy the expected derivative commutator. -/
theorem qPolynomial_mul_p_sub (f : MvPolynomial ι K) (k : ι) :
    qPolynomial K ι f * p K ι k - p K ι k * qPolynomial K ι f =
      qPolynomial K ι (pderiv k f) := by
  induction f using MvPolynomial.induction_on with
  | C a =>
      simp only [qPolynomial_C, pderiv_C, map_zero]
      exact sub_eq_zero.mpr (Algebra.commutes a (p K ι k))
  | add f g hf hg =>
      simp only [map_add, map_add] at hf hg ⊢
      rw [← hf, ← hg]
      noncomm_ring
  | mul_X f i hf =>
      simp only [map_mul, qPolynomial_X, pderiv_mul, pderiv_X, map_add, map_mul]
      rw [← hf]
      by_cases h : i = k
      · subst i
        simp
        have hraw := q_mul_p_sub K ι k k
        rw [if_pos rfl, map_one] at hraw
        have hqp : q K ι k * p K ι k = p K ι k * q K ι k + 1 :=
          sub_eq_iff_eq_add'.mp hraw
        noncomm_ring [hqp]
      · simp [h]
        have hraw := q_mul_p_sub K ι i k
        rw [if_neg h, map_zero] at hraw
        have hqp : q K ι i * p K ι k = p K ι k * q K ι i := by
          exact sub_eq_zero.mp hraw
        noncomm_ring [hqp]

end ExoticCCR
